### PR TITLE
Python3

### PR DESCRIPTION
**Pull request by HarleyB123**
This will probably need work over time, and I'm sure there are much smarter people than me who can do this better - but this is my stab at it :D 

I've not got the OS requirements in the README, but as an FYI both my version and the shell script don't work for me on MacOS - Might be worth creating an issue for that.

Let me know if the python way works as intended on your OS :)

### CODE REVIEW

**Comment by dmccuk** [comment]
Hi Harley,

Thanks for the python3 code. I really appreciate it!

In the Readme, I mention RHEL8 & Unbuntu 16/18.04. I can't test on a Mac as I don't have one (on purpose!)

 I've set up your branch on one of my test servers on AWS. If you want to test it out for yourself, you can log in and have a play.

I noticed this when I tested it just now:

1) the pyhon3 script didn't create the /tmp/ansible DIR. It should if it doesn't exist
2) Once I create /tmp/ansible, the script ran with no issues but the tasks didn't get picked up:

I'll send you over the login details if you want to try it for yourself.

Regards

Dennis

**Comment by HarleyB123** [comment]
Hey @dmccuk ,

Just fixed the creation of the directory (called the function in the wrong order). Seen what you mean about the tasks not being picked up - working on that.

Ran the shell script and got this output- not sure if thats intended?:

```sh AnsiblePlaybookGenerator.sh 
AnsiblePlaybookGenerator.sh: 11: AnsiblePlaybookGenerator.sh: source: not found
mkdir: cannot create directory ‘/tmp/ansible_files’: File exists
 ** Error: No ansible.cfg. **
 **     Creating now... **

Putting all the files in the /tmp/ansible_files DIR:
 ** OK: Directory /tmp/ansible_files exists. **
Creating the other directories we need
AnsiblePlaybookGenerator.sh: 99: AnsiblePlaybookGenerator.sh: cannot create /tmp/ansible_files/group_vars/all: Directory nonexistent
AnsiblePlaybookGenerator.sh: 110: AnsiblePlaybookGenerator.sh: cannot create /tmp/ansible_files/group_vars/all: Directory nonexistent
AnsiblePlaybookGenerator.sh: 115: AnsiblePlaybookGenerator.sh: cannot create /tmp/ansible_files/tasks/webserver.yml: Directory nonexistent
AnsiblePlaybookGenerator.sh: 126: AnsiblePlaybookGenerator.sh: cannot create /tmp/ansible_files/tasks/webserver.yml: Directory nonexistent
AnsiblePlaybookGenerator.sh: 134: AnsiblePlaybookGenerator.sh: cannot create /tmp/ansible_files/group_vars/all: Directory nonexistent
AnsiblePlaybookGenerator.sh: 142: AnsiblePlaybookGenerator.sh: cannot create /tmp/ansible_files/tasks/webserver.yml: Directory nonexistent
AnsiblePlaybookGenerator.sh: 159: AnsiblePlaybookGenerator.sh: cannot create /tmp/ansible_files/templates/index.html.j2: Directory nonexistent
AnsiblePlaybookGenerator.sh: 110: AnsiblePlaybookGenerator.sh: cannot create /tmp/ansible_files/group_vars/all: Directory nonexistent
AnsiblePlaybookGenerator.sh: 115: AnsiblePlaybookGenerator.sh: cannot create /tmp/ansible_files/tasks/vsftpd.yml: Directory nonexistent
AnsiblePlaybookGenerator.sh: 126: AnsiblePlaybookGenerator.sh: cannot create /tmp/ansible_files/tasks/vsftpd.yml: Directory nonexistent
AnsiblePlaybookGenerator.sh: 134: AnsiblePlaybookGenerator.sh: cannot create /tmp/ansible_files/group_vars/all: Directory nonexistent
AnsiblePlaybookGenerator.sh: 142: AnsiblePlaybookGenerator.sh: cannot create /tmp/ansible_files/tasks/vsftpd.yml: Directory nonexistent
AnsiblePlaybookGenerator.sh: 159: AnsiblePlaybookGenerator.sh: cannot create /tmp/ansible_files/templates/vsftpd.conf.j2: Directory nonexistent
AnsiblePlaybookGenerator.sh: 110: AnsiblePlaybookGenerator.sh: cannot create /tmp/ansible_files/group_vars/all: Directory nonexistent
AnsiblePlaybookGenerator.sh: 115: AnsiblePlaybookGenerator.sh: cannot create /tmp/ansible_files/tasks/wget.yml: Directory nonexistent
AnsiblePlaybookGenerator.sh: 110: AnsiblePlaybookGenerator.sh: cannot create /tmp/ansible_files/group_vars/all: Directory nonexistent
AnsiblePlaybookGenerator.sh: 115: AnsiblePlaybookGenerator.sh: cannot create /tmp/ansible_files/tasks/curl.yml: Directory nonexistent
ls: cannot access '/tmp/ansible_files/tasks': No such file or directory
total 24
drwxrwxr-x  3 ubuntu ubuntu 4096 Apr  7 08:05 .
drwxrwxrwt 10 root   root   4096 Apr  7 08:05 ..
-rw-rw-r--  1 ubuntu ubuntu  231 Apr  7 08:05 ansible.cfg
-rw-rw-r--  1 ubuntu ubuntu   54 Apr  7 08:05 inventory
-rw-rw-r--  1 ubuntu ubuntu  242 Apr  7 08:05 run.yml
drwxrwxr-x  2 ubuntu ubuntu 4096 Apr  7 08:05 {tasks,templates,group_vars}```

**Comment by dmccuk** [comment]
Can you try running the script like this:

$ ./AnsiblePlaybookGenerator.sh

The script is set up to use the Bash shell (#!/bin/bash) and it's already executable. It looks like your forcing it to run as the "sh" (shell) which doesn't support the "sources" functionality that bash does (sources allows you to take variables from a remote file into your code). Which is why you get the error.

The other messages:

`mkdir: cannot create directory ‘/tmp/ansible_files’: File exists
 ** OK: ansible.cfg exists. **

Putting all the files in the /tmp/ansible_files DIR:
 ** OK: Directory /tmp/ansible_files exists. **
Creating the other directories we need
`
Are only for information really. Reading them back I think I'll remove them as they don't look great.

Thanks for creating the python3 code for me. I appreciate your help. Once the tasks get populated, I'd like to promote your collaboration on my LinkedIn page.

I had to use sed in my script to position the tasks in the correct place after tasks: but before handlers:

This bottom line is interesting:
drwxrwxr-x 2 ubuntu ubuntu 4096 Apr 7 08:05 {tasks,templates,group_vars}

It should be expanding them out into directories inside /tmp/ansible. That may be related to using sh instead of just ./

Let me know what you get back.

Dennis

**Comment by HarleyB123** [comment]
Ah I see, ok - have seen the expected output of run.yml. Will try and get to working on that this week :)

**Comment by HarleyB123** [comment]
Well that was much quicker to do than I thought!

Below is my ansible ouput:
```
ansible-playbook -i inventory run.yml

PLAY [localhost] *******************************************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************************************
ok: [localhost]

TASK [install package nginx] *******************************************************************************************************************************************************************************
changed: [localhost]

TASK [Enable service nginx] ********************************************************************************************************************************************************************************
ok: [localhost]

TASK [template] ********************************************************************************************************************************************************************************************
changed: [localhost]

TASK [install package vsftpd] ******************************************************************************************************************************************************************************
changed: [localhost]

TASK [Enable service vsftpd] *******************************************************************************************************************************************************************************
ok: [localhost]

TASK [template] ********************************************************************************************************************************************************************************************
changed: [localhost]

TASK [install package wget] ********************************************************************************************************************************************************************************
ok: [localhost]

TASK [install package curl] ********************************************************************************************************************************************************************************
ok: [localhost]

RUNNING HANDLER [restart nginx] ****************************************************************************************************************************************************************************
changed: [localhost]

RUNNING HANDLER [restart vsftpd] ***************************************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP *************************************************************************************************************************************************************************************************
localhost                  : ok=11   changed=6    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0 ```

**Comment by dmccuk** [comment]
I just tested it myself with your latest commit and its working on ubuntu 18.04 & RHEL7.8.

Nice work Harley, I'll merge it shortly and update the README to include running the python3 script.

Thanks!

**Pull request merged**
